# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: Deploy Nikola to GitHub Pages
    steps:
    - name: Check out
      uses: actions/checkout@v3
#   - name: Cache things
#     uses: actions/cache@v2
    - name: Build and Deploy Nikola
      uses: paddy-hack/nikola:8.3.0
      with:
        dry_run: false
